### ISSUE TITLE
Use assetlinks.json instead of manifest?

### ISSUE THREAD

**Issue by ithinkihaveacat** [WICG/get-installed-related-apps#4]
Why is the manifest used for the web side of the link instead of [`/.well-known/assetlinks.json`](https://developers.google.com/digital-asset-links/)?

`assetlinks.json` is already used for features such as Smart Lock, and a number of sites for which this feature would be useful already have the asset links configured (Twitter, Facebook).

**Comment by mgiuca** [comment]
Google Digital Asset Links is an Android-specific standard controlled by Google. It serves a similar functionality to the the [`related_applications`](https://www.w3.org/TR/appmanifest/#related_applications-member) field of the manifest (in fact, `related_applications` is inspired by DAL and recently received the fingerprints feature from DAL).

The difference is that the manifest is designed to be platform-neutral and is specified through W3C (not tied to Google and Android). As you can see, we've made some effort to avoid being tied to any particular implementation, e.g., by having generic "fingerprints" instead of "sha_256_fingerprints", generic "id" instead of "package_name", etc. But it serves the same purpose.

I think it will be much easier to get cross-browser support for this feature if we use the agreed upon manifest format instead of an Android-specific file. Plausibly, we could add a fallback to assetlinks.json in the Chrome-for-Android implementation of getInstalledRelatedApps, later down the line.
