### ISSUE TITLE
About “related_applications” in manifest.json

### ISSUE THREAD

**Issue by hillmanchen** [WICG/get-installed-related-apps#7]
Hi buddy, I found that every application object in "related_applications" should contains a "platform" member, "play" for Android && "itunes" for iOS. Is that means IT ONLY WORKS ON G-PLAY when using Android? Are there any other "platform" options could be placed? 

Cuz we have many different 'Android like' OS installed by different phone maker, here, in China. Each OS has it's own AppStore so, I want to know if there is a way could solve this problem -- like support more platform or any else...

**Comment by marcoscaceres** [comment]
Yeah, the working assumption is that the OS and browser provides the integration. Do any of these smaller Android-like OSs plan to support web manifest integration? They could, in theory, just say that they support "play".

**Comment by hillmanchen** [comment]
Got. But I thought it might be difficult to achieve that goal..  OS owners are now building their closed ecology, what they concerned first was taking control of appstore and payment, like HUAWEI Store, MI Store, etc.. It would be a long way to push them support that 'platform' standard.  Maybe browser here can go further.

Will still pay attention to this issue.

**Comment by marcoscaceres** [comment]
Our goal is still for users to install PWAs (and for developers to not push users onto native applications), but not to encourage them to use `related_applications`. 

The `related_applications` is a very regrettable feature from this perspective. From this perspective, the store fragmentation is actually a good thing, because it will hopefully encourage more developers to build for the web instead. 

closing, as there is no action we can take here.

**Comment by hopperhuang** [comment]
@hillmanchen Hi, buddy, hava you ever found the methods get the native app installed with other platform, like: huawei store , mi store etc. I am focus on this fucntion, recently. thanks~~!!
